name: "Run command in a Flox environment"
description: "Runs a command in the context of the Flox environment."
author: "flox <hello@floxdev.com>"

branding:
  color: "blue"
  icon: "moon"

inputs:
  command:
    description: "A command to run inside the Flox environment."
    required: true
  environment:
    description: "Environment to run the command in. If not specified it will try to find local Flox environment."
    default: null
  dir:
    description: "Path containing a .flox/ directory."
    default: null

runs:
  using: "composite"
  steps:
    - name: "Run flox activate"
      shell: "bash"
      run: "flox activate ${{ inputs.environment != null && format('-r={0}', inputs.environment) || '' }} ${{ inputs.dir != null && format('--dir={0}', inputs.dir) || '' }} -- ${{ inputs.command }}"
